print("System message imminent!")
print("System robot has been initiated")
print()
print()
print("......rebooting sensory system.")
print("......rebooting output motors.")
print("......hover engine.")
print()
print()
print("System online.")