print("Pls enter the number of lives:")
lives = int(input())
print("Pls enter the energy level:")
energy = int(input())
print("pls enter the shield level:")
shield = int(input())
print(f"lives:{'&#100704'* lives}")
print(f"energy:{'E'* energy}")
print(f"shield:{'S'*shield}")